package cn.edu.nju.software.storymapping.map.dao;

import cn.edu.nju.software.storymapping.map.entity.ActivityCard;
import cn.edu.nju.software.storymapping.map.entity.ActivityCardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    long countByExample(ActivityCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int deleteByExample(ActivityCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int insert(ActivityCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int insertSelective(ActivityCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    List<ActivityCard> selectByExample(ActivityCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    ActivityCard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") ActivityCard record, @Param("example") ActivityCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByExample(@Param("record") ActivityCard record, @Param("example") ActivityCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByPrimaryKeySelective(ActivityCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByPrimaryKey(ActivityCard record);
}