package cn.edu.nju.software.storymapping.map.dao;

import cn.edu.nju.software.storymapping.map.entity.Release;
import cn.edu.nju.software.storymapping.map.entity.ReleaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReleaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    long countByExample(ReleaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int deleteByExample(ReleaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int insert(Release record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int insertSelective(Release record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    List<Release> selectByExample(ReleaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    Release selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") Release record, @Param("example") ReleaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByExample(@Param("record") Release record, @Param("example") ReleaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByPrimaryKeySelective(Release record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table release
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByPrimaryKey(Release record);
}