package cn.edu.nju.software.storymapping.map.dao;

import cn.edu.nju.software.storymapping.map.entity.SubTaskCard;
import cn.edu.nju.software.storymapping.map.entity.SubTaskCardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubTaskCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    long countByExample(SubTaskCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int deleteByExample(SubTaskCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int insert(SubTaskCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int insertSelective(SubTaskCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    List<SubTaskCard> selectByExample(SubTaskCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    SubTaskCard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") SubTaskCard record, @Param("example") SubTaskCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByExample(@Param("record") SubTaskCard record, @Param("example") SubTaskCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByPrimaryKeySelective(SubTaskCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByPrimaryKey(SubTaskCard record);
}