package cn.edu.nju.software.storymapping.map.dao;

import cn.edu.nju.software.storymapping.map.entity.TaskCard;
import cn.edu.nju.software.storymapping.map.entity.TaskCardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    long countByExample(TaskCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int deleteByExample(TaskCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int insert(TaskCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int insertSelective(TaskCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    List<TaskCard> selectByExample(TaskCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    TaskCard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaskCard record, @Param("example") TaskCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByExample(@Param("record") TaskCard record, @Param("example") TaskCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByPrimaryKeySelective(TaskCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByPrimaryKey(TaskCard record);
}