package cn.edu.nju.software.storymapping.map.dao;

import cn.edu.nju.software.storymapping.map.entity.Workspace;
import cn.edu.nju.software.storymapping.map.entity.WorkspaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkspaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_space
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    long countByExample(WorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_space
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int deleteByExample(WorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_space
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_space
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int insert(Workspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_space
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int insertSelective(Workspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_space
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    List<Workspace> selectByExample(WorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_space
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    Workspace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_space
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") Workspace record, @Param("example") WorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_space
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByExample(@Param("record") Workspace record, @Param("example") WorkspaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_space
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByPrimaryKeySelective(Workspace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_space
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    int updateByPrimaryKey(Workspace record);
}