spring:
  profiles:
    include: devdb
  thymeleaf:
    cache: false
  session:
    jdbc:
      initialize-schema: ALWAYS
    store-type: jdbc


logging:
  level:
    cn.edu.nju.software.storymapping.map.dao: DEBUG
