spring:
  profiles:
    active: dev

server:
  port: 8090

mybatis:
  mapper-locations: classpath:mapper/map/*Mapper.xml,classpath:mapper/system/*Mapper.xml
  #type-aliases-package: cn.edu.nju.software.storymapping.system.entity
  configuration:
    map-underscore-to-camel-case: true

#showSql
logging:
  level:
    com:
      example:
        mapper: debug

#启用内容版本策略 md5
spring.resources.chain.strategy.content.enabled: true
#应用于版本策略的模式的逗号分隔列表 默认/**
spring.resources.chain.strategy.content.paths: /**
