spring:
  datasource:
    username: story_map
    password: story_mapqwe123456
    url: jdbc:mysql://172.19.240.117:3306/story_map?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver