spring:
  profiles:
    include: devdb
  thymeleaf:
    cache: false
  session:
    jdbc:
      initialize-schema: ALWAYS
    store-type: jdbc
server:
  session:
    cookie:
      max-age: 10000
    timeout: 10000


logging:
  level:
    cn.edu.nju.software.storymapping.map.dao: DEBUG
