spring:
  datasource:
    username: story_map
    password: story_map123
    url: jdbc:mysql://localhost:3306/story_map?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver