package cn.edu.nju.software.storymapping.map.entity;

import java.util.Date;
import java.util.List;

public class ActivityCard implements Orderable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_card.id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_card.description
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_card.creator_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_card.create_time
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_card.color
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_card.story_map_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Integer storyMapId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_card.order
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_card.name
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String name;

    private List<TaskCard> taskCardList;
    
    private List<Role> roleList;

    public List<Role> getRoleList() {
		return roleList;
	}

	public void setRoleList(List<Role> roleList) {
		this.roleList = roleList;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public ActivityCard(Integer id, String description, Integer creatorId, Date createTime, String color, Integer storyMapId, String order, String name) {
        this.id = id;
        this.description = description;
        this.creatorId = creatorId;
        this.createTime = createTime;
        this.color = color;
        this.storyMapId = storyMapId;
        this.order = order;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public ActivityCard() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_card.id
     *
     * @return the value of activity_card.id
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    public List<TaskCard> getTaskCardList() {
        return taskCardList;
    }

    public void setTaskCardList(List<TaskCard> taskCardList) {
        this.taskCardList = taskCardList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_card.id
     *
     * @param id the value for activity_card.id
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_card.description
     *
     * @return the value of activity_card.description
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_card.description
     *
     * @param description the value for activity_card.description
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_card.creator_id
     *
     * @return the value of activity_card.creator_id
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_card.creator_id
     *
     * @param creatorId the value for activity_card.creator_id
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_card.create_time
     *
     * @return the value of activity_card.create_time
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_card.create_time
     *
     * @param createTime the value for activity_card.create_time
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_card.color
     *
     * @return the value of activity_card.color
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_card.color
     *
     * @param color the value for activity_card.color
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_card.story_map_id
     *
     * @return the value of activity_card.story_map_id
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Integer getStoryMapId() {
        return storyMapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_card.story_map_id
     *
     * @param storyMapId the value for activity_card.story_map_id
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setStoryMapId(Integer storyMapId) {
        this.storyMapId = storyMapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_card.order
     *
     * @return the value of activity_card.order
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_card.order
     *
     * @param order the value for activity_card.order
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setOrder(String order) {
        this.order = order == null ? null : order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_card.name
     *
     * @return the value of activity_card.name
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_card.name
     *
     * @param name the value for activity_card.name
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Override
    public String toString() {
        return "ActivityCard{" +
                "id=" + id +
                ", description='" + description + '\'' +
                ", creatorId=" + creatorId +
                ", createTime=" + createTime +
                ", color='" + color + '\'' +
                ", storyMapId=" + storyMapId +
                ", order='" + order + '\'' +
                ", name='" + name + '\'' +
                ", taskCardList=" + taskCardList +
                '}';
    }
}