package cn.edu.nju.software.storymapping.map.entity;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.url
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.category
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Image(Integer id, String url, String category) {
        this.id = id;
        this.url = url;
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Image() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.url
     *
     * @return the value of image.url
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.url
     *
     * @param url the value for image.url
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.category
     *
     * @return the value of image.category
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.category
     *
     * @param category the value for image.category
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }
}