package cn.edu.nju.software.storymapping.map.entity;

import java.util.Date;

public class SubTaskCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_task_card.id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_task_card.description
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_task_card.creator_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_task_card.create_time
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_task_card.color
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_task_card.task_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_task_card.order
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_task_card.release_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Integer releaseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_task_card.name
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sub_task_card.status
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public SubTaskCard(Integer id, String description, Integer creatorId, Date createTime, String color, Integer taskId, String order, Integer releaseId, String name, String status) {
        this.id = id;
        this.description = description;
        this.creatorId = creatorId;
        this.createTime = createTime;
        this.color = color;
        this.taskId = taskId;
        this.order = order;
        this.releaseId = releaseId;
        this.name = name;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public SubTaskCard() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_task_card.id
     *
     * @return the value of sub_task_card.id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_task_card.id
     *
     * @param id the value for sub_task_card.id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_task_card.description
     *
     * @return the value of sub_task_card.description
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_task_card.description
     *
     * @param description the value for sub_task_card.description
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_task_card.creator_id
     *
     * @return the value of sub_task_card.creator_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_task_card.creator_id
     *
     * @param creatorId the value for sub_task_card.creator_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_task_card.create_time
     *
     * @return the value of sub_task_card.create_time
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_task_card.create_time
     *
     * @param createTime the value for sub_task_card.create_time
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_task_card.color
     *
     * @return the value of sub_task_card.color
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_task_card.color
     *
     * @param color the value for sub_task_card.color
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_task_card.task_id
     *
     * @return the value of sub_task_card.task_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_task_card.task_id
     *
     * @param taskId the value for sub_task_card.task_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_task_card.order
     *
     * @return the value of sub_task_card.order
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_task_card.order
     *
     * @param order the value for sub_task_card.order
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setOrder(String order) {
        this.order = order == null ? null : order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_task_card.release_id
     *
     * @return the value of sub_task_card.release_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Integer getReleaseId() {
        return releaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_task_card.release_id
     *
     * @param releaseId the value for sub_task_card.release_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setReleaseId(Integer releaseId) {
        this.releaseId = releaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_task_card.name
     *
     * @return the value of sub_task_card.name
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_task_card.name
     *
     * @param name the value for sub_task_card.name
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sub_task_card.status
     *
     * @return the value of sub_task_card.status
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sub_task_card.status
     *
     * @param status the value for sub_task_card.status
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    @Override
    public String toString() {
        return "SubTaskCard{" +
                "id=" + id +
                ", description='" + description + '\'' +
                ", creatorId=" + creatorId +
                ", createTime=" + createTime +
                ", color='" + color + '\'' +
                ", taskId=" + taskId +
                ", order='" + order + '\'' +
                ", releaseId=" + releaseId +
                ", name='" + name + '\'' +
                ", status='" + status + '\'' +
                '}';
    }
}