package cn.edu.nju.software.storymapping.map.entity;

import java.util.Date;
import java.util.List;

public class TaskCard implements Orderable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_card.id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_card.description
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_card.creator_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_card.create_time
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_card.color
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_card.activity_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_card.order
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_card.name
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String name;
    private List<SubTaskCard> subTaskCardList;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public TaskCard(Integer id, String description, Integer creatorId, Date createTime, String color, Integer activityId, String order, String name) {
        this.id = id;
        this.description = description;
        this.creatorId = creatorId;
        this.createTime = createTime;
        this.color = color;
        this.activityId = activityId;
        this.order = order;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_card
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public TaskCard() {
        super();
    }


    public List<SubTaskCard> getSubTaskCardList() {
        return subTaskCardList;
    }

    public void setSubTaskCardList(List<SubTaskCard> subTaskCardList) {
        this.subTaskCardList = subTaskCardList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_card.id
     *
     * @return the value of task_card.id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_card.id
     *
     * @param id the value for task_card.id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_card.description
     *
     * @return the value of task_card.description
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_card.description
     *
     * @param description the value for task_card.description
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_card.creator_id
     *
     * @return the value of task_card.creator_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_card.creator_id
     *
     * @param creatorId the value for task_card.creator_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_card.create_time
     *
     * @return the value of task_card.create_time
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_card.create_time
     *
     * @param createTime the value for task_card.create_time
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_card.color
     *
     * @return the value of task_card.color
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_card.color
     *
     * @param color the value for task_card.color
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_card.activity_id
     *
     * @return the value of task_card.activity_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_card.activity_id
     *
     * @param activityId the value for task_card.activity_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_card.order
     *
     * @return the value of task_card.order
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_card.order
     *
     * @param order the value for task_card.order
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setOrder(String order) {
        this.order = order == null ? null : order.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_card.name
     *
     * @return the value of task_card.name
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_card.name
     *
     * @param name the value for task_card.name
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Override
    public String toString() {
        return "TaskCard{" +
                "id=" + id +
                ", description='" + description + '\'' +
                ", creatorId=" + creatorId +
                ", createTime=" + createTime +
                ", color='" + color + '\'' +
                ", activityId=" + activityId +
                ", order='" + order + '\'' +
                ", name='" + name + '\'' +
                ", subTaskCardList=" + subTaskCardList +
                '}';
    }
}