package cn.edu.nju.software.storymapping.map.entity;

import java.util.Date;

public class Workspace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_space.id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_space.name
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_space.user_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_space.description
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work_space.create_time
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_space
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Workspace(Integer id, String name, Integer userId, String description, Date createTime) {
        this.id = id;
        this.name = name;
        this.userId = userId;
        this.description = description;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work_space
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Workspace() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_space.id
     *
     * @return the value of work_space.id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_space.id
     *
     * @param id the value for work_space.id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_space.name
     *
     * @return the value of work_space.name
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_space.name
     *
     * @param name the value for work_space.name
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_space.user_id
     *
     * @return the value of work_space.user_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_space.user_id
     *
     * @param userId the value for work_space.user_id
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_space.description
     *
     * @return the value of work_space.description
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_space.description
     *
     * @param description the value for work_space.description
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work_space.create_time
     *
     * @return the value of work_space.create_time
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work_space.create_time
     *
     * @param createTime the value for work_space.create_time
     *
     * @mbg.generated Sat Dec 22 16:48:12 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}